### ISSUE TITLE
The web app is not getting rendered yet

### ISSUE THREAD

**Issue by sambhavsaxena** [NuroDev/nuro.dev#55]
Hey Ben,
I tried deploying my build several times but I'm still getting slow loading for unknown reasons. 
The build in dev mode took seconds but on production mode, the one being deployed on vercel and netlify are loading super slowly.
And not just mine, I forked your master branch and deployed it using vercel, but the issue still persists.

This is the maximum content loaded after waiting for 10 minutes.
![image](https://user-images.githubusercontent.com/76242518/181307415-e74b4e9b-095f-4699-9104-da1a79d7cff8.png)

Suggestions pls????

**Comment by NuroDev** [comment]
Thanks for reporting this I was actually not aware that the latest production build was broken.

I've found the cause. Last night when fixing #54 I also upgraded the Next.js version to 12.2.3 & local development server seemed to work fine so I assumed it was a simple upgrade.

However, after running a local production build it replicates the error you have shown above. The reason is because of [`preact`](https://preactjs.com/).

In production builds `react` is replaced with [`preact`](https://preactjs.com/) & it seems the newer versions of [`next`](https://nextjs.org/) don't like the current / old method I have implemented. For now I have disabled / commented out for now. I may look at adding it back in again later on using [the official `next` plugin](https://github.com/preactjs/next-plugin-preact) instead but for now just deployed a fix for it.
